import type { Hall } from "./types";

export const halls: Hall[] = [
  {
    id: "pasar-tebet-sport-center",
    name: "Pasar Tebet Sport Center",
    address: "Jl. Tebet Barat Dalam Raya No. 12, Tebet, Jakarta Selatan",
    description:
      "A community-driven complex with well-maintained courts suitable for casual games, leagues, and private coaching sessions.",
    priceRange: "Rp 40.000/session",
    amenities: [
      "Equipment rental",
      "Locker room & showers",
      "On-site cafe",
      "Dedicated parking",
    ],
    rows: [
      {
        number: 1,
        orientation: "horizontal",
        courts: [
          { label: "14", isAvailable: false },
          { label: "15", isAvailable: false },
        ],
      },
      {
        number: 2,
        orientation: "vertical",
        courts: [
          { label: "9" },
          { label: "10" },
          { label: "11" },
          { label: "12", isAvailable: false },
          { label: "13", isAvailable: false },
        ],
      },
    ],
    players: [
      { name: "Andri", gender: "man", skillLevel: "intermediate" },
      { name: "Fahri", gender: "woman", skillLevel: "beginner" },
      { name: "Dinda", gender: "woman", skillLevel: "novice" },
      { name: "Ryo", gender: "man", skillLevel: "pro" },
      { name: "Bagus", gender: "man", skillLevel: "advanced" },
      { name: "Ricardo", gender: "man", skillLevel: "intermediate" },
      { name: "Rifqi", gender: "woman", skillLevel: "beginner" },
      { name: "Mar Galo 1", gender: "man", skillLevel: "pro" },
      { name: "Pak Ardi", gender: "man", skillLevel: "advanced" },
      { name: "Dzaki", gender: "woman", skillLevel: "novice" },
      { name: "Pak Bob", gender: "man", skillLevel: "intermediate" },
      { name: "Radit", gender: "woman", skillLevel: "beginner" },
      { name: "Pak Ery", gender: "man", skillLevel: "pro" },
      { name: "Nikho", gender: "man", skillLevel: "advanced" },
      { name: "Akmal FS", gender: "woman", skillLevel: "intermediate" },
      { name: "Putra", gender: "man", skillLevel: "novice" },
      { name: "Caithlyn", gender: "woman", skillLevel: "beginner" },
      { name: "Mattew", gender: "man", skillLevel: "pro" },
      { name: "Fai", gender: "woman", skillLevel: "intermediate" },
      { name: "Herman", gender: "man", skillLevel: "advanced" },
      { name: "Ahmad", gender: "woman", skillLevel: "novice" },
      { name: "Ridho", gender: "man", skillLevel: "pro" },
      { name: "Carlo", gender: "man", skillLevel: "beginner" },
      { name: "Ken", gender: "woman", skillLevel: "intermediate" },
      { name: "Alvin Chandra", gender: "man", skillLevel: "advanced" },
      { name: "Reza F", gender: "woman", skillLevel: "novice" },
      { name: "Bang Ef", gender: "man", skillLevel: "pro" },
      { name: "Ardy", gender: "man", skillLevel: "beginner" },
      { name: "Yofri", gender: "woman", skillLevel: "intermediate" },
      { name: "Kiky", gender: "woman", skillLevel: "pro" },
    ],
  },
  {
    id: "jifi-arena-badminton",
    name: "JiFi Arena Badminton",
    address: "Jl. Kemang Raya No. 45, Mampang Prapatan, Jakarta Selatan",
    description:
      "Modern indoor arena offering tournament-grade lighting and flooring, favored by intermediate and advanced players.",
    priceRange: "Rp 50.000/session",
    amenities: [
      "Professional coaching",
      "Stringing service",
      "Pro shop",
      "Cafeteria",
    ],
    rows: [
      {
        number: 1,
        orientation: "vertical",
        courts: [
          { label: "1", isAvailable: false },
          { label: "2" },
          { label: "3" },
        ],
      },
    ],
    players: [
      { name: "Alvaro", gender: "man", skillLevel: "advanced" },
      { name: "gandi", gender: "man", skillLevel: "intermediate" },
      { name: "Leo", gender: "woman", skillLevel: "beginner" },
      { name: "Jalu", gender: "man", skillLevel: "novice" },
      { name: "Sikri", gender: "woman", skillLevel: "intermediate" },
      { name: "Mar", gender: "man", skillLevel: "advanced" },
      { name: "harry", gender: "man", skillLevel: "beginner" },
      { name: "debby", gender: "woman", skillLevel: "novice" },
      { name: "Defri", gender: "man", skillLevel: "intermediate" },
      { name: "Bima", gender: "man", skillLevel: "pro" },
      { name: "fandu", gender: "man", skillLevel: "beginner" },
      { name: "Via", gender: "woman", skillLevel: "intermediate" },
      { name: "Joy", gender: "man", skillLevel: "advanced" },
      { name: "Martin", gender: "man", skillLevel: "novice" },
      { name: "zeni", gender: "woman", skillLevel: "intermediate" },
      { name: "yayan", gender: "man", skillLevel: "pro" },
      { name: "delby Adrian", gender: "man", skillLevel: "advanced" },
      { name: "hanif", gender: "man", skillLevel: "intermediate" },
      { name: "laala_aja", gender: "woman", skillLevel: "beginner" },
      { name: "mr wit", gender: "man", skillLevel: "advanced" },
      { name: "Devid", gender: "man", skillLevel: "novice" },
      { name: "Rudi", gender: "woman", skillLevel: "intermediate" },
      { name: "chaterine", gender: "woman", skillLevel: "beginner" },
      { name: "Yofri", gender: "man", skillLevel: "advanced" },
      { name: "robby", gender: "man", skillLevel: "novice" },
      { name: "temen alvaro", gender: "woman", skillLevel: "intermediate" },
      { name: "jeremy", gender: "man", skillLevel: "beginner" },
    ],
  },
];

export const getHallById = (id: string) =>
  halls.find((hall) => hall.id === id);
