/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules.index'
import { Route as HallsIndexRouteImport } from './routes/halls.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SchedulesCreateRouteImport } from './routes/schedules.create'
import { Route as SchedulesIdRouteImport } from './routes/schedules.$id'
import { Route as HallsCreateRouteImport } from './routes/halls.create'
import { Route as HallsIdRouteImport } from './routes/halls.$id'
import { Route as ApiSchedulesRouteImport } from './routes/api.schedules'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiTenantProfileRouteImport } from './routes/api.tenant.profile'
import { Route as ApiTenantPlayersRouteImport } from './routes/api.tenant.players'
import { Route as ApiTenantHallsRouteImport } from './routes/api.tenant.halls'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiSchedulesIdPlayersRouteImport } from './routes/api.schedules.$id.players'
import { Route as ApiHallsHallIdRegisteredPlayersRouteImport } from './routes/api.halls.$hallId.registered-players'
import { Route as ApiHallsHallIdPlayersRouteImport } from './routes/api.halls.$hallId.players'
import { Route as ApiHallsHallIdCourtsRouteImport } from './routes/api.halls.$hallId.courts'
import { Route as ApiAdminUsersIdConfirmRouteImport } from './routes/api.admin.users.$id.confirm'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsIndexRoute = HallsIndexRouteImport.update({
  id: '/halls/',
  path: '/halls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesCreateRoute = SchedulesCreateRouteImport.update({
  id: '/schedules/create',
  path: '/schedules/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIdRoute = SchedulesIdRouteImport.update({
  id: '/schedules/$id',
  path: '/schedules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsCreateRoute = HallsCreateRouteImport.update({
  id: '/halls/create',
  path: '/halls/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsIdRoute = HallsIdRouteImport.update({
  id: '/halls/$id',
  path: '/halls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesRoute = ApiSchedulesRouteImport.update({
  id: '/api/schedules',
  path: '/api/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantProfileRoute = ApiTenantProfileRouteImport.update({
  id: '/api/tenant/profile',
  path: '/api/tenant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantPlayersRoute = ApiTenantPlayersRouteImport.update({
  id: '/api/tenant/players',
  path: '/api/tenant/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantHallsRoute = ApiTenantHallsRouteImport.update({
  id: '/api/tenant/halls',
  path: '/api/tenant/halls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchedulesIdPlayersRoute = ApiSchedulesIdPlayersRouteImport.update({
  id: '/$id/players',
  path: '/$id/players',
  getParentRoute: () => ApiSchedulesRoute,
} as any)
const ApiHallsHallIdRegisteredPlayersRoute =
  ApiHallsHallIdRegisteredPlayersRouteImport.update({
    id: '/api/halls/$hallId/registered-players',
    path: '/api/halls/$hallId/registered-players',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHallsHallIdPlayersRoute = ApiHallsHallIdPlayersRouteImport.update({
  id: '/api/halls/$hallId/players',
  path: '/api/halls/$hallId/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHallsHallIdCourtsRoute = ApiHallsHallIdCourtsRouteImport.update({
  id: '/api/halls/$hallId/courts',
  path: '/api/halls/$hallId/courts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIdConfirmRoute = ApiAdminUsersIdConfirmRouteImport.update({
  id: '/$id/confirm',
  path: '/$id/confirm',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/halls/$id': typeof HallsIdRoute
  '/halls/create': typeof HallsCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/halls/': typeof HallsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tenant/halls': typeof ApiTenantHallsRoute
  '/api/tenant/players': typeof ApiTenantPlayersRoute
  '/api/tenant/profile': typeof ApiTenantProfileRoute
  '/api/halls/$hallId/courts': typeof ApiHallsHallIdCourtsRoute
  '/api/halls/$hallId/players': typeof ApiHallsHallIdPlayersRoute
  '/api/halls/$hallId/registered-players': typeof ApiHallsHallIdRegisteredPlayersRoute
  '/api/schedules/$id/players': typeof ApiSchedulesIdPlayersRoute
  '/api/admin/users/$id/confirm': typeof ApiAdminUsersIdConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/halls/$id': typeof HallsIdRoute
  '/halls/create': typeof HallsCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/halls': typeof HallsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tenant/halls': typeof ApiTenantHallsRoute
  '/api/tenant/players': typeof ApiTenantPlayersRoute
  '/api/tenant/profile': typeof ApiTenantProfileRoute
  '/api/halls/$hallId/courts': typeof ApiHallsHallIdCourtsRoute
  '/api/halls/$hallId/players': typeof ApiHallsHallIdPlayersRoute
  '/api/halls/$hallId/registered-players': typeof ApiHallsHallIdRegisteredPlayersRoute
  '/api/schedules/$id/players': typeof ApiSchedulesIdPlayersRoute
  '/api/admin/users/$id/confirm': typeof ApiAdminUsersIdConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/schedules': typeof ApiSchedulesRouteWithChildren
  '/halls/$id': typeof HallsIdRoute
  '/halls/create': typeof HallsCreateRoute
  '/schedules/$id': typeof SchedulesIdRoute
  '/schedules/create': typeof SchedulesCreateRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/halls/': typeof HallsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tenant/halls': typeof ApiTenantHallsRoute
  '/api/tenant/players': typeof ApiTenantPlayersRoute
  '/api/tenant/profile': typeof ApiTenantProfileRoute
  '/api/halls/$hallId/courts': typeof ApiHallsHallIdCourtsRoute
  '/api/halls/$hallId/players': typeof ApiHallsHallIdPlayersRoute
  '/api/halls/$hallId/registered-players': typeof ApiHallsHallIdRegisteredPlayersRoute
  '/api/schedules/$id/players': typeof ApiSchedulesIdPlayersRoute
  '/api/admin/users/$id/confirm': typeof ApiAdminUsersIdConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/api/schedules'
    | '/halls/$id'
    | '/halls/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/settings/profile'
    | '/halls/'
    | '/schedules/'
    | '/settings/'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/tenant/halls'
    | '/api/tenant/players'
    | '/api/tenant/profile'
    | '/api/halls/$hallId/courts'
    | '/api/halls/$hallId/players'
    | '/api/halls/$hallId/registered-players'
    | '/api/schedules/$id/players'
    | '/api/admin/users/$id/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/api/schedules'
    | '/halls/$id'
    | '/halls/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/settings/profile'
    | '/halls'
    | '/schedules'
    | '/settings'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/tenant/halls'
    | '/api/tenant/players'
    | '/api/tenant/profile'
    | '/api/halls/$hallId/courts'
    | '/api/halls/$hallId/players'
    | '/api/halls/$hallId/registered-players'
    | '/api/schedules/$id/players'
    | '/api/admin/users/$id/confirm'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/api/schedules'
    | '/halls/$id'
    | '/halls/create'
    | '/schedules/$id'
    | '/schedules/create'
    | '/settings/profile'
    | '/halls/'
    | '/schedules/'
    | '/settings/'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/tenant/halls'
    | '/api/tenant/players'
    | '/api/tenant/profile'
    | '/api/halls/$hallId/courts'
    | '/api/halls/$hallId/players'
    | '/api/halls/$hallId/registered-players'
    | '/api/schedules/$id/players'
    | '/api/admin/users/$id/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiSchedulesRoute: typeof ApiSchedulesRouteWithChildren
  HallsIdRoute: typeof HallsIdRoute
  HallsCreateRoute: typeof HallsCreateRoute
  SchedulesIdRoute: typeof SchedulesIdRoute
  SchedulesCreateRoute: typeof SchedulesCreateRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  HallsIndexRoute: typeof HallsIndexRoute
  SchedulesIndexRoute: typeof SchedulesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTenantHallsRoute: typeof ApiTenantHallsRoute
  ApiTenantPlayersRoute: typeof ApiTenantPlayersRoute
  ApiTenantProfileRoute: typeof ApiTenantProfileRoute
  ApiHallsHallIdCourtsRoute: typeof ApiHallsHallIdCourtsRoute
  ApiHallsHallIdPlayersRoute: typeof ApiHallsHallIdPlayersRoute
  ApiHallsHallIdRegisteredPlayersRoute: typeof ApiHallsHallIdRegisteredPlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls/': {
      id: '/halls/'
      path: '/halls'
      fullPath: '/halls/'
      preLoaderRoute: typeof HallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/create': {
      id: '/schedules/create'
      path: '/schedules/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof SchedulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/$id': {
      id: '/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof SchedulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls/create': {
      id: '/halls/create'
      path: '/halls/create'
      fullPath: '/halls/create'
      preLoaderRoute: typeof HallsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls/$id': {
      id: '/halls/$id'
      path: '/halls/$id'
      fullPath: '/halls/$id'
      preLoaderRoute: typeof HallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules': {
      id: '/api/schedules'
      path: '/api/schedules'
      fullPath: '/api/schedules'
      preLoaderRoute: typeof ApiSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/profile': {
      id: '/api/tenant/profile'
      path: '/api/tenant/profile'
      fullPath: '/api/tenant/profile'
      preLoaderRoute: typeof ApiTenantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/players': {
      id: '/api/tenant/players'
      path: '/api/tenant/players'
      fullPath: '/api/tenant/players'
      preLoaderRoute: typeof ApiTenantPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant/halls': {
      id: '/api/tenant/halls'
      path: '/api/tenant/halls'
      fullPath: '/api/tenant/halls'
      preLoaderRoute: typeof ApiTenantHallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schedules/$id/players': {
      id: '/api/schedules/$id/players'
      path: '/$id/players'
      fullPath: '/api/schedules/$id/players'
      preLoaderRoute: typeof ApiSchedulesIdPlayersRouteImport
      parentRoute: typeof ApiSchedulesRoute
    }
    '/api/halls/$hallId/registered-players': {
      id: '/api/halls/$hallId/registered-players'
      path: '/api/halls/$hallId/registered-players'
      fullPath: '/api/halls/$hallId/registered-players'
      preLoaderRoute: typeof ApiHallsHallIdRegisteredPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/halls/$hallId/players': {
      id: '/api/halls/$hallId/players'
      path: '/api/halls/$hallId/players'
      fullPath: '/api/halls/$hallId/players'
      preLoaderRoute: typeof ApiHallsHallIdPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/halls/$hallId/courts': {
      id: '/api/halls/$hallId/courts'
      path: '/api/halls/$hallId/courts'
      fullPath: '/api/halls/$hallId/courts'
      preLoaderRoute: typeof ApiHallsHallIdCourtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id/confirm': {
      id: '/api/admin/users/$id/confirm'
      path: '/$id/confirm'
      fullPath: '/api/admin/users/$id/confirm'
      preLoaderRoute: typeof ApiAdminUsersIdConfirmRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
  }
}

interface ApiSchedulesRouteChildren {
  ApiSchedulesIdPlayersRoute: typeof ApiSchedulesIdPlayersRoute
}

const ApiSchedulesRouteChildren: ApiSchedulesRouteChildren = {
  ApiSchedulesIdPlayersRoute: ApiSchedulesIdPlayersRoute,
}

const ApiSchedulesRouteWithChildren = ApiSchedulesRoute._addFileChildren(
  ApiSchedulesRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdConfirmRoute: typeof ApiAdminUsersIdConfirmRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdConfirmRoute: ApiAdminUsersIdConfirmRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiSchedulesRoute: ApiSchedulesRouteWithChildren,
  HallsIdRoute: HallsIdRoute,
  HallsCreateRoute: HallsCreateRoute,
  SchedulesIdRoute: SchedulesIdRoute,
  SchedulesCreateRoute: SchedulesCreateRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  HallsIndexRoute: HallsIndexRoute,
  SchedulesIndexRoute: SchedulesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTenantHallsRoute: ApiTenantHallsRoute,
  ApiTenantPlayersRoute: ApiTenantPlayersRoute,
  ApiTenantProfileRoute: ApiTenantProfileRoute,
  ApiHallsHallIdCourtsRoute: ApiHallsHallIdCourtsRoute,
  ApiHallsHallIdPlayersRoute: ApiHallsHallIdPlayersRoute,
  ApiHallsHallIdRegisteredPlayersRoute: ApiHallsHallIdRegisteredPlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
